name: Generate Changelog

on:
  push:
    branches:
      - main  # O tu rama principal de desarrollo
  pull_request:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # O la versión de Node.js que uses

      - name: Install dependencies
        run: |
          npm install

      - name: Install standard-version
        run: |
          npm install --save-dev standard-version

      - name: Generate Changelog
        run: |
          npx standard-version --release-as minor

      - name: Configure Git user
        run: |
          git config user.name "JeanCHV"
          git config user.email "jc_26.10@hotmail.com"

      - name: Commit changelog and version changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'JeanCHV'  # Reemplaza con tu nombre de usuario de GitHub
          author_email: 'jc_26.10@hotmail.com'  # Reemplaza con tu correo de GitHub
          message: 'chore(release): update changelog and version'
          branch: main
