name: Changelog CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Revisa el repositorio
      - uses: actions/checkout@v2

      # Configura la identidad de git
      - name: Set Git identity
        run: |
          git config --global user.name "JeanCHV"
          git config --global user.email "jc_26.10@hotmail.com"

      # Ejecuta el Changelog CI
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-ci-config.json
          committer_username: 'JeanCHV'
          committer_email: 'jc_26.10@hotmail.com'
          release_version: ${{ github.event.inputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
