name: Changelog CI

on:
  push:
    branches:
      - main  # O tu rama principal de desarrollo
  pull_request:
    branches:
      - main

  # Optionally you can use `workflow_dispatch` to run Changelog CI Manually
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          # Optional, you can provide any name for your changelog file,
          # We currently support Markdown (.md) and reStructuredText (.rst) files
          changelog_filename: CHANGELOG.md
          # Configuración personalizada para organizar el changelog
          config_file: changelog-ci-config.json
          # Configura el autor para los commits de changelog
          committer_username: 'JeanCHV'
          committer_email: 'jc_26.10@hotmail.com'
          # Entrada manual de la versión de lanzamiento
          release_version: ${{ github.event.inputs.release_version }}
          # Token de GitHub para autenticarse
          github_token: ${{ secrets.GITHUB_TOKEN }}
